### ISSUE TITLE
Custom Login Providers

### ISSUE THREAD

**Issue by zorab47** [igorkasyanchuk/any_login#14]
Before adding this, I want to get feedback on the idea. The concept is to allow custom providers that can integrate with other authentication libraries.

Currently, I can assign a custom provider class to the the AnyLogin configuration (see below). But it throws a message (that becomes an exception). Where could I `catch` the message? Is there an alternate implementation that would check for the existence of the constant then decide if the `throw` is necessary?

```ruby
AnyLogin.setup do |config|
  config.provider = MyCustomProvider
end
```

https://github.com/igorkasyanchuk/any_login/blob/edc5737cec60c245486021dde70b8c6834f939a8/lib/any_login/engine.rb#L34

**Comment by igorkasyanchuk** [comment]
@zorab47 how do you plan to manage session and methods like "current_user"?
If you have everything working, you can make a PR, or at least share code samples. thanks

**Comment by zorab47** [comment]
I mainly wanted to override the `any_login_sign_in` functionality. My use case is based on Devise, but I didn't want to log in as a different user. I wanted to update a ActiveRecord model to impersonate another user's privileges. 

So, it is primarily to customize the `any_login_sign_in` method.

**Comment by igorkasyanchuk** [comment]
for a long time, no one want's to fix so I'm closing it
