### ISSUE TITLE
Support multiple model?

### ISSUE THREAD

**Issue by sajjadmurtaza** [igorkasyanchuk/any_login#20]
I have 4 different devise model and i am using any_login gem https://github.com/igorkasyanchuk/any_login

But it is limited to switching users from the same model.

Is there is another solution to be able to switch users in development. How any_login gem to support multiple user models.

**Comment by igorkasyanchuk** [comment]
It supports one at least this is 100%, also 90% I believe it supports STI

As for multiple (different) models I'm not sure, since it was not a my case.

I suggest for you try to clone repo, open dummy app and try to replicate case what you have
