### ISSUE TITLE
DEPRECATION WARNING: `Module#parent_name` has been renamed to `module_parent_name`. `parent_name` is deprecated and will be removed in Rails 6.1

### ISSUE THREAD

**Issue by saiqulhaq** [igorkasyanchuk/any_login#23]
I got deprecation warning when I call `<%= any_login_here if defined?(AnyLogin) %>` method on my views file

**Comment by saiqulhaq** [comment]
is it because this code https://github.com/igorkasyanchuk/any_login/blob/723b7691348381317a1851e95c0e86829daeccb8/lib/any_login.rb#L97?

**Comment by igorkasyanchuk** [comment]
@saiqulhaq could you please add a fix, check if Rails 6+ use new method and if older - use current method?

**Comment by igorkasyanchuk** [comment]
merged, and released a new version. thanks!
