### ISSUE TITLE
Support for apps running a more restrictive Content Security Policy

### ISSUE THREAD

**Issue by rbclark** [igorkasyanchuk/any_login#48]
I am only running this application in development (and not in prod), however it would be very useful it were structured in a manner where the application could still run locally without having to modify the content security policy for development. Currently this gem requires the enabling of unsafe inline for script source and style source.

There are likely two ways to fix this:
1. Move the css and javascript into their own dedicated files.
2. Add the ability to use nonces with the javascript and css.

I'd like to take a stab at moving the css and javascript into their own dedicated files in order to solve this problem. Do you have any thoughts/objections?

**Comment by igorkasyanchuk** [comment]
No objection. The only comment what I have we use this app for staging too. So application can be deployed so js css should be in assets precompile or another option is to add 2 rails routes and just stream them with appropriate content type
