### ISSUE TITLE
MongoDB integration

### ISSUE THREAD

**Issue by Nekromancer** [igorkasyanchuk/any_login#6]
I have new project with devise on MongoDB (mongoid). Code `<%= any_login_here %>` rises an error that it doesn't exists

**Comment by igorkasyanchuk** [comment]
MongoDB doesn't supported. I really doesn't know it) so any help is appreciated)

**Comment by igorkasyanchuk** [comment]
Maybe someone wants to make a PR?

**Comment by bbenezech** [comment]
@igorkasyanchuk https://github.com/igorkasyanchuk/any_login/blob/master/lib/any_login.rb#L118
You use ActiveRecord::Relation without testing with `defined?`, this may be a problem.

What is the difference between `result.limit(limit)` and `result.take(limit)`?

Otherwise the rest of the codebase seems ORM agnostic, it only assumes a `Model.find(__ID__)` method to select user.

@Nekromancer as a quick fix you can try to deactivate the select dropdown for now.

**Comment by igorkasyanchuk** [comment]
limit(x) I'm using for AR relations, and take(x) for arrays

**Comment by bbenezech** [comment]
@igorkasyanchuk maybe the limit thing is too low level.

Maybe all we need is:

1. Offer a default dropdown with max100 users (to protect application from blowing up)
2. A proc option to get an `[id, label]` array, with no assumption on anything.

What do you think?

**Comment by igorkasyanchuk** [comment]
I think some users may want to have >100 users which is OK, put we can put 100 as default value for limit.
yes, we may have such proc, but we need to support grouped collections too (which is I'm personally using on 2 mine projects, where I need to login as users with different roles, so I've 10 users for each role)

**Comment by bbenezech** [comment]
Let the user build select options with a nice example for grouped options in the readme, then?

**Comment by igorkasyanchuk** [comment]
Documentation is there
https://github.com/igorkasyanchuk/any_login#advanced-options? or you
speaking about some other things?

**Comment by bbenezech** [comment]
No, that looks perfect.

**Comment by shivabhusal** [comment]
I am also using `Mongoid`, when I select a user from the drop-down, I see this error.
`NoMethodError in Dashboards#index`
<img width="1139" alt="image" src="https://user-images.githubusercontent.com/8004593/58849592-9c847700-86aa-11e9-8d48-1fcae3a85724.png">

**Comment by igorkasyanchuk** [comment]
Now it supports: https://github.com/igorkasyanchuk/any_login#mongoid

Maybe it would be possible to check if model is a class of Mongo model we can define this "primary" method on the fly to avoid manual work?
