### ISSUE TITLE
Multiple models

### ISSUE THREAD

**Issue by chrise86** [igorkasyanchuk/any_login#9]
More of a feature request than an issue, would be great if it worked with multiple models (with Devise in my case).

**Comment by igorkasyanchuk** [comment]
it can work with multiple models, for example "Account", but only one model at same time.

**Comment by chrise86** [comment]
Yes sorry that is what I meant, multiple models simultaneously.

**Comment by igorkasyanchuk** [comment]
I don't think this feature will be implemented soon, sorry just don't have enough time. But id you can open a pr it would be great

**Comment by zorab47** [comment]
@chrise86 Do your models have distinct identifiers? Or is it necessary to distinguish between them using something like [GlobalID](https://github.com/rails/globalid)?

**Comment by igorkasyanchuk** [comment]
for a long time, no one want's to fix so I'm closing it
